
social:
  fab fa-github: https://github.com/wodiu188 || Github
  fas fa-envelope: mailto:1834519329@qq.com || Email

menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标籤: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    音乐: /music/ || fas fa-music
#    照片: /Gallery/ || fas fa-images
#    电影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link # 关于: /about/ || fas fa-heart

avatar:
  img: /img/fund.jpeg
  effect: false # 头像会一直转圈

index_img: 'linear-gradient(20deg, #0062be, #925696, #cc426e, #fb0347)'
archive_img: '#D24D57'

error_404:
  enable: true
  background: img/404.jpeg

aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手机页面（ 显示宽度 < 768px ）是否显示aside内容
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Github
      link: https://github.com/jerryc127/hexo-theme-butterfly
  card_announcement: # 公告栏
    enable: false
    content: asdfasdf
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true


canvas_ribbon:
  enable: true
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false  #設置是否每次點擊都更換綵帶
  mobile: false # false 手機端不顯示 true 手機端顯示


